### ISSUE TITLE
Cant run Nightly version of youscope

### ISSUE THREAD

**Issue by TunjiK** [langmo/youscope#13]
Im trying to run a PI-E662 and an Amscope MU1403 in MM or Youscope on windows. Micro manager will work fine the first time the program is opened but will crash after closing and reopening. I was glad to have found an alternative to the micro manager UI that also seemed more polished, but there is no Amscope support in R2018 and when I tried the newest nightly version to date the program would crash after the first dialog...

```
ConnectionFailedException: Could not initialize microscope with given configuration file.
InvocationTargetException: null
UnsupportedClassVersionError: mmcorej/CMMCore : Unsupported major.minor version 52.0

Stack Trace:
Server.java, Line 198
Server.java, Line 71
Starter.java, Line 853
```

I briefly tried to compile the program from source but I got an error when using gradle...

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/tunji/Documents/gitProgs/copyYouScope/build.gradle' line: 10

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.langmo.gradlensis', version: '0.1.0']
> Failed to apply plugin [id 'com.github.langmo.gradlensis']
   > Could not generate a proxy class for class com.github.langmo.gradlensis.GradleNsisPluginExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

So I was hoping I could get some help with this either fixing the newer version or getting pointers on how to build from source and add custom drivers.

**Comment by langmo** [comment]
Hi,
sorry for the late reply. Due to Corona, I am currently very occupied in changing courses to online teaching and didn't have a lot of time for anything else.
I just checked the newest nightly build and it started normally (i.e. I couldn't reproduce your error at startup). Are you starting YS with the default configuration (YSConfig_demo.cfg) or with an empty configuration? If not, please try so and eventually try to add your devices manually in YS. If the error still persists, can you send me the files error_client.txt and error_server.txt, which are located in the YS folder (right after YS crashed, the files are overwritten every time you start YS).
Also, you might want to try to check if there is some MicroManager folder in the windows path/environmental variables and remove it. YS is build on the MM drivers, and the error indicates that there is a version conflict between the drivers YS expect and the drivers which are actually found.
Also the gradle installer works fine at my computer, as well as on the github repository. The error you get concerns a gradle plugin which is automatically creating an NSIS installer for YS once YS is build. It only runs on Windows machines and temporary installs some binaries (i.e. NSIS), thus my guess is that you are either not on a Windows machine or you are running the installer without sufficient priviliges. Either way, it would be sufficient to comment out line 10 (where the plugin is loaded) as well as everything below line 326 (where the plugin is applied). You won't be able to automatically create an installer for YS, but I guess this should be OK ;)

**Comment by TunjiK** [comment]
Its totally fine, I got it working by using Java 8 instead of Java 7. But
do you have any experience with using amscope cameras?

**Comment by langmo** [comment]
Good to hear that everything works. No, sorry, no direct experience with amscope.
