### ISSUE TITLE
Use with a stupid camera

### ISSUE THREAD

**Issue by KOLANICH** [langmo/youscope#7]
Hello. I wonder if it is very hard to add a stupid camera mode. I mean use the image captured by any capture device in the system like a webcam or analog capture device and just translate pixels into microns using a fixed ratio. I mean that we have just an analog microscope with hand-rotated gauges, just added a camera there for better convenience and capturing pictures.

**Comment by langmo** [comment]
Hi. As far as I understand, you want to use a webcam (or similar devices) as a substitute for a "real camera" , and then to be able to control this webcam together with other devices via YouScope. In principal, adding such a feature is possible, and I long ago also thought about it to simplify debugging. One possibility would be to add a new camera device type, which is essentially nothing else than a wrapper around the TWAIN API (https://en.wikipedia.org/wiki/TWAIN ). Every device which supports the TWAIN standard (many webcams, but also scanners) could then be used as a substitute for a "real camera".
This task can be roughly split up into several steps: (i) Writing a functions which discovers (via the TWAIN API) all currently installed TWAIN devices; (ii) Writing a function which takes the name/identifier of a TWAIN device as an input, and connects to this device; (iii) Writing a function which makes an image with a connected TWAIN device, and returns the image e.g. as an array of bytes; (iv) Mapping this functionality to YouScope.
I don't know how experienced you are in programming, specifically, in C/C++.  In principal, steps i-iii have nothing to do with YouScope, and I would have no advantage trying to accomplish them only because I know YS. For step iv, I have a clear advantage. Thus I could offer to do step iv if you or somebody else would take over step i-iii and send me the source code (C/C++). I have currently a lot to do, and would thus not know when I would find time if I would have to do everything on myself...sorry.

**Comment by KOLANICH** [comment]
>Hi. As far as I understand, you want to use a webcam (or similar devices) as a substitute for a "real camera" , and then to be able to control this webcam together with other devices via YouScope

Not quite, it's pretty uncontrolable, it just sends the picture. I want the following workflow:
1 i put something with known size on the glass
2 I draw an interval on screen with mouse and input its size
3 the software remembers the ratio
4 then I can draw intervals on image and measure their sizes
5 there should be multiple ratios remembered, since the device is driven manually. for example the minimum zoom and maximum zoom
6 for the continious magnifying the software should determine the zoom by matching the contents of the neibouring frames to each other, for example with SIFT, SURF or other descriptors and compute the affine transform (there exists an example hiw to do it in opencv)

>  (i) Writing a functions which discovers (via the TWAIN API) all currently installed TWAIN devices; (ii) Writing a function which takes the name/identifier of a TWAIN device as an input, and connects to this device; (iii) Writing a function which makes an image with a connected TWAIN device, and returns the image e.g. as an array of bytes; 

I wonder if opencv highgui module has it. I have used it with a webcam some time ago.

**Comment by langmo** [comment]
The simplest thing which I forgot: There is already a TWAIN driver in YS/MM! Just follow the documentation provided at https://micro-manager.org/wiki/TwainCamera . If you are lucky, it might work (if you are asked for a camera ID, a good guess is to take "0", but you might also simply try all numbers from 0-9...)
OpenCV also seems to support it, but I didn't try: https://docs.opencv.org/3.4.1/d8/dfe/classcv_1_1VideoCapture.html . The example at the bottom of the page looks like they internally use TWAIN.

Considering your workflow: Are you sure that for what you want to do a microscope control software like YS (or any other) is actually the right kind of application? Essentially, your workflow rather sounds like a custom GUI around some custom image processing task with the additional feature to get an image from a camera (either continuously or when you press a button). That this camera is actually connected to a completely manual microscope seems to be a rather minor detail. The point is, there exist specialized software to do microscope control (e.g. YS), and specialized software to do image processing (e.g. ImageJ). Even though YS offers some elementary functionality to look at images, zoom & draw some lines, this is definitely not YS main purpose. Similar to this elementary support of image processing in YS, most specialized image processing software has some elementary support for capturing images from a camera, scanner, or similar. It seems that such elementary support would be totally sufficient for you since the rest of the microscope is anyway completely manually controlled, if I understand completely.

So, without wanting to convince you not to use YS, you might for this specific task consider to use
- ImageJ: https://imagej.nih.gov/ij/plugins/webcam-capture/index.html 
- Matlab: https://www.mathworks.com/help/supportpkg/usbwebcams/ug/snapshot.html
- Python using OpenCV or similar: https://stackoverflow.com/questions/11094481/capturing-a-single-image-from-my-webcam-in-java-or-python
- C++ using OpenCV
- Java/Jython: https://stackoverflow.com/questions/276292/capturing-image-from-webcam-in-java

Essentially, all of this software allows you to take images from a Webcam or Scanner, do some image processing and to build a GUI around it. YS is mainly written in Java, so if you would want you could write a plugin for YS (I can help with the YS side), but a standalone application would probably work as well. For the latter, feel free to "steal" the YS code to display an image, zoom and draw lines (it's open source): https://github.com/langmo/youscope/blob/master/youscope-addon/src/org/youscope/uielements/ImagePanel.java
Note that Java offers no support for unsigned numbers, which is a bit inconvenient for programs with a focus on image processing. You could also write the GUI in Java and the processing in Matlab (it's easy to talk to Java from Matlab), or use the combination Java/Jython (Jython=Python which can easily talk to Java). C++ is IMO too low level for your task...

In case I misunderstood what you want to do, please tell me!
